# Generated by Django 3.1.7 on 2021-03-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAVAsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentManagementService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_item', models.CharField(max_length=150)),
            ],
        ),
    ]
