# Generated by Django 3.1.7 on 2021-03-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAVAsite', '0002_contentmanagementservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmanagementservice',
            name='list_item_2',
            field=models.CharField(default='second item', max_length=150),
        ),
    ]
