# Generated by Django 3.1.7 on 2021-03-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAVAsite', '0003_contentmanagementservice_list_item_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentmanagementservice',
            name='list_item',
        ),
        migrations.RemoveField(
            model_name='contentmanagementservice',
            name='list_item_2',
        ),
        migrations.AddField(
            model_name='contentmanagementservice',
            name='content_management_service_1',
            field=models.CharField(default='Service Item', max_length=150),
        ),
        migrations.AddField(
            model_name='contentmanagementservice',
            name='content_management_service_10',
            field=models.CharField(default='Service Item', max_length=150),
        ),
        migrations.AddField(
            model_name='contentmanagementservice',
            name='content_management_service_2',
            field=models.CharField(default='Service Item', max_length=150),
        ),
        migrations.AddField(
            model_name='contentmanagementservice',
            name='content_management_service_3',
            field=models.CharField(default='Service Item', max_length=150),
        ),
        migrations.AddField(
            model_name='contentmanagementservice',
            name='content_management_service_4',
            field=models.CharField(default='Service Item', max_length=150),
        ),
        migrations.AddField(
            model_name='contentmanagementservice',
            name='content_management_service_5',
            field=models.CharField(default='Service Item', max_length=150),
        ),
        migrations.AddField(
            model_name='contentmanagementservice',
            name='content_management_service_6',
            field=models.CharField(default='Service Item', max_length=150),
        ),
        migrations.AddField(
            model_name='contentmanagementservice',
            name='content_management_service_7',
            field=models.CharField(default='Service Item', max_length=150),
        ),
        migrations.AddField(
            model_name='contentmanagementservice',
            name='content_management_service_8',
            field=models.CharField(default='Service Item', max_length=150),
        ),
        migrations.AddField(
            model_name='contentmanagementservice',
            name='content_management_service_9',
            field=models.CharField(default='Service Item', max_length=150),
        ),
    ]
